# Generated by Django 4.1.6 on 2023-03-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_area_alter_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nearby',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
