# Generated by Django 4.1.6 on 2023-02-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pic',
            field=models.ImageField(default='', upload_to='\\userprofile'),
            preserve_default=False,
        ),
    ]
