# Generated by Django 4.1.6 on 2023-02-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pic',
            field=models.ImageField(upload_to='C:\\Users\\Dell\\Desktop\\Voting\\Vs\\accounts\\userprofile'),
        ),
    ]
