# Generated by Django 4.1.6 on 2023-02-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='aadhar_no',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
