# Generated by Django 4.1.6 on 2023-02-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electionlist',
            name='type',
            field=models.CharField(choices=[('Loksabha', 'Loksabha'), ('Assembly', 'Assembly'), ('Panchayat', 'Panchayat')], max_length=255),
        ),
    ]
