# Generated by Django 4.1.6 on 2023-03-01 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_remove_uservote_custom_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electionlist',
            name='custom_user',
        ),
        migrations.AddField(
            model_name='electionlist',
            name='candidate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_id', to='homeapp.candidate'),
        ),
    ]
