# Generated by Django 4.1.6 on 2023-03-01 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0004_remove_electionlist_custom_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electionlist',
            name='region',
        ),
    ]
