# Generated by Django 4.1.6 on 2023-03-07 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0007_remove_electionlist_type_electionlist_electionid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electionlist',
            name='electionid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='election_id', to='homeapp.electiontype'),
        ),
    ]
