# Generated by Django 4.1.6 on 2023-03-07 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0008_alter_electionlist_electionid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electionlist',
            name='electionid',
        ),
    ]
