# Generated by Django 4.1.6 on 2023-03-07 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0009_remove_electionlist_electionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionlist',
            name='election_type_fk',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='homeapp.electiontype'),
        ),
    ]
