# Generated by Django 4.1.6 on 2023-03-07 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0010_electionlist_election_type_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='election_type_fk',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='homeapp.electiontype'),
        ),
    ]
